# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
