# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Frontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
   'Core',
   'CxxBridge', # Include this for RN >= 0.47
   'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
   'RCTNetwork',
   'RCTText',
   'RCTAnimation', # Needed for FlatList and animations running on native UI thread
]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
